name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: ibakshay/github-project-automation-plus@main
        with:
          project: test-project
          column: triage
          repo-token: ${{ secrets.test }}
